name: build-operator

on: [workflow_dispatch]

jobs:
  build-operator:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3

      - name: build
        run: |
          VERSION=$(git describe | awk -F '-' '{print $1}')
          docker login registry.hub.docker.com -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_PASSWORD }}" 2>/dev/null
          cd ./source-code/operator && make docker-build
          docker tag controller:latest registry.hub.docker.com/lukaspastva/${{ github.event.repository.name }}-operator:latest
          docker tag controller:latest registry.hub.docker.com/lukaspastva/${{ github.event.repository.name }}-operator:${VERSION}
          docker push registry.hub.docker.com/lukaspastva/${{ github.event.repository.name }}-operator:latest
          docker push registry.hub.docker.com/lukaspastva/${{ github.event.repository.name }}-operator:${VERSION}